/**
 * ASC Simphonic II subscription agreement, as a digital template.
 *
 * GENERATED by scripts/import-legal-doc.mjs from counsel's .docx. The
 * wording and the section structure are counsel's; only the typography
 * and the {{merge}} tokens are ours. Do not hand-edit: re-run the
 * importer when the source document changes.
 *
 * Every clause carries the confirmation panel that discharges it, so the
 * document and the panels can never disagree about what was agreed.
 */
import type { LegalDocument } from './types';

export const SUBSCRIPTION_AGREEMENT: LegalDocument = {
  "title": "SUBSCRIPTION AGREEMENT",
  "subtitle": [
    "for",
    "CLASS B COMMON UNITS",
    "of",
    "ASC SIMPHONIC II, LLC",
    "(a Delaware limited liability company)",
    "THE SECURITIES OFFERED HEREBY HAVE NOT BEEN REGISTERED UNDER THE U.S. SECURITIES ACT OF 1933, AS AMENDED (THE “SECURITIES ACT”), OR THE SECURITIES LAWS OF ANY STATE, AND ARE BEING OFFERED AND SOLD IN RELIANCE ON EXEMPTIONS FROM THE REGISTRATION REQUIREMENTS OF THE SECURITIES ACT AND APPLICABLE STATE SECURITIES LAWS. THE SECURITIES ARE BEING OFFERED ONLY TO PERSONS WHO QUALIFY AS “ACCREDITED INVESTORS” AS DEFINED IN RULE 501(a) OF REGULATION D PROMULGATED UNDER THE SECURITIES ACT.",
    "THE SECURITIES MAY NOT BE OFFERED, SOLD, TRANSFERRED, PLEDGED, HYPOTHECATED, OR OTHERWISE DISPOSED OF EXCEPT IN ACCORDANCE WITH THE OPERATING AGREEMENT OF THE COMPANY AND APPLICABLE LAW. NO PUBLIC MARKET EXISTS OR IS EXPECTED TO DEVELOP FOR THE SECURITIES. INVESTORS MUST BE PREPARED TO BEAR THE ECONOMIC RISK OF THIS INVESTMENT FOR AN INDEFINITE PERIOD AND TO RISK A TOTAL LOSS OF THEIR INVESTMENT.",
    "PRIOR TO EXECUTING THIS SUBSCRIPTION AGREEMENT, EACH PROSPECTIVE INVESTOR SHOULD CAREFULLY REVIEW THE CONFIDENTIAL PRIVATE PLACEMENT MEMORANDUM OF THE COMPANY DATED [●], 2026 (THE “MEMORANDUM”) AND THE OPERATING AGREEMENT OF THE COMPANY (THE “OPERATING AGREEMENT”), AND CONSULT WITH SUCH INVESTOR’S OWN LEGAL, TAX, AND FINANCIAL ADVISORS.",
    "INSTRUCTIONS TO PROSPECTIVE INVESTORS",
    "In order to subscribe for Class B Common Units (the “Class B Units” or the “Securities”) of ASC Simphonic II, LLC, a Delaware limited liability company (the “Company”), each prospective investor (a “Subscriber”) must:",
    "The Manager (as defined below) may, in its sole and absolute discretion, accept or reject any subscription, in whole or in part. A subscription is not binding on the Company until accepted by the Manager. If a subscription is rejected (or accepted only in part), the rejected portion of the Subscription Amount will be returned to the Subscriber without interest or deduction.",
    "All inquiries should be directed to:",
    "AltSpot Capital, LLC",
    "as Manager of ASC Simphonic II, LLC",
    "Attn: Ryan Billings",
    "3101 Ocean Park Blvd, Santa Monica, CA 90405",
    "Email: contact@thealtspot.com",
    "Telephone: (310) 351-7347",
    "SUBSCRIPTION AGREEMENT",
    "This SUBSCRIPTION AGREEMENT (this “Subscription Agreement” or this “Agreement”) is entered into as of the date set forth on the signature page hereto (the “Subscription Date”), by and between ASC Simphonic II, LLC, a Delaware limited liability company (the “Company”), and the undersigned subscriber (the “Subscriber”).",
    "Capitalized terms used and not otherwise defined in this Agreement shall have the meanings ascribed to such terms in the Memorandum or in the Operating Agreement of the Company, dated as of May 15, 2026 (as the same may be amended, supplemented, or restated from time to time, the “Operating Agreement”).",
    "WHEREAS, the Company is a Delaware limited liability company formed for the sole purpose of acquiring and holding shares of Series B Preferred Stock (the “Series B Preferred”) of Simphonic, Inc., a Delaware corporation (“Simphonic”), together with associated warrants to purchase common stock of Simphonic (the “Warrants” and, together with the Series B Preferred, the “Portfolio Securities”);",
    "WHEREAS, the Company is offering Class B Common Units (the “Class B Units” or the “Securities”) to a limited number of “accredited investors” as defined in Rule 501(a) of Regulation D promulgated under the Securities Act, in reliance on the exemption from registration provided by Section 4(a)(2) of the Securities Act and Rule 506 of Regulation D, and applicable state securities law exemptions (the “Offering”);",
    "WHEREAS, AltSpot Capital, LLC serves as the Manager of the Company (the “Manager”); and",
    "WHEREAS, the Subscriber wishes to subscribe for, and the Company wishes to issue and sell to the Subscriber, the number of Class B Units set forth on the signature page hereto, on and subject to the terms and conditions of this Agreement and the Operating Agreement.",
    "NOW, THEREFORE, in consideration of the foregoing recitals and the mutual covenants and agreements contained herein, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the parties agree as follows:"
  ],
  "articles": [
    {
      "numeral": null,
      "title": "PREAMBLE",
      "blocks": [
        {
          "type": "p",
          "text": "for"
        },
        {
          "type": "p",
          "text": "CLASS B COMMON UNITS"
        },
        {
          "type": "p",
          "text": "of"
        },
        {
          "type": "p",
          "text": "ASC SIMPHONIC II, LLC"
        },
        {
          "type": "p",
          "text": "(a Delaware limited liability company)"
        },
        {
          "type": "p",
          "text": "THE SECURITIES OFFERED HEREBY HAVE NOT BEEN REGISTERED UNDER THE U.S. SECURITIES ACT OF 1933, AS AMENDED (THE “SECURITIES ACT”), OR THE SECURITIES LAWS OF ANY STATE, AND ARE BEING OFFERED AND SOLD IN RELIANCE ON EXEMPTIONS FROM THE REGISTRATION REQUIREMENTS OF THE SECURITIES ACT AND APPLICABLE STATE SECURITIES LAWS. THE SECURITIES ARE BEING OFFERED ONLY TO PERSONS WHO QUALIFY AS “ACCREDITED INVESTORS” AS DEFINED IN RULE 501(a) OF REGULATION D PROMULGATED UNDER THE SECURITIES ACT."
        },
        {
          "type": "p",
          "text": "THE SECURITIES MAY NOT BE OFFERED, SOLD, TRANSFERRED, PLEDGED, HYPOTHECATED, OR OTHERWISE DISPOSED OF EXCEPT IN ACCORDANCE WITH THE OPERATING AGREEMENT OF THE COMPANY AND APPLICABLE LAW. NO PUBLIC MARKET EXISTS OR IS EXPECTED TO DEVELOP FOR THE SECURITIES. INVESTORS MUST BE PREPARED TO BEAR THE ECONOMIC RISK OF THIS INVESTMENT FOR AN INDEFINITE PERIOD AND TO RISK A TOTAL LOSS OF THEIR INVESTMENT."
        },
        {
          "type": "p",
          "text": "PRIOR TO EXECUTING THIS SUBSCRIPTION AGREEMENT, EACH PROSPECTIVE INVESTOR SHOULD CAREFULLY REVIEW THE CONFIDENTIAL PRIVATE PLACEMENT MEMORANDUM OF THE COMPANY DATED [●], 2026 (THE “MEMORANDUM”) AND THE OPERATING AGREEMENT OF THE COMPANY (THE “OPERATING AGREEMENT”), AND CONSULT WITH SUCH INVESTOR’S OWN LEGAL, TAX, AND FINANCIAL ADVISORS."
        },
        {
          "type": "item",
          "text": "Review the Offering Documents. Read this Subscription Agreement, the Memorandum, and the Operating Agreement in their entirety, and consult with the Subscriber’s own legal, tax, and financial advisors."
        },
        {
          "type": "item",
          "text": "Complete this Subscription Agreement. Complete and execute the signature pages to this Subscription Agreement, including the Subscription Amount and all other required information."
        },
        {
          "type": "item",
          "text": "Complete the Accredited Investor Questionnaire. Complete and execute the Accredited Investor Questionnaire attached hereto as Exhibit A."
        },
        {
          "type": "item",
          "text": "Execute the Operating Agreement Counterpart Signature Page. Complete and execute the counterpart signature page to the Operating Agreement attached hereto as Exhibit B."
        },
        {
          "type": "item",
          "text": "Provide Identification and Anti-Money Laundering Documentation. Provide such identification and other anti-money laundering documentation as the Manager may reasonably request."
        },
        {
          "type": "item",
          "text": "Submit Documents and Funds. Return all completed and executed documents and wire the Subscription Amount in accordance with the wire instructions provided by the Manager."
        },
        {
          "type": "p",
          "text": "The Manager (as defined below) may, in its sole and absolute discretion, accept or reject any subscription, in whole or in part. A subscription is not binding on the Company until accepted by the Manager. If a subscription is rejected (or accepted only in part), the rejected portion of the Subscription Amount will be returned to the Subscriber without interest or deduction."
        },
        {
          "type": "p",
          "text": "All inquiries should be directed to:"
        },
        {
          "type": "p",
          "text": "AltSpot Capital, LLC"
        },
        {
          "type": "p",
          "text": "as Manager of ASC Simphonic II, LLC"
        },
        {
          "type": "p",
          "text": "Attn: Ryan Billings"
        },
        {
          "type": "p",
          "text": "3101 Ocean Park Blvd, Santa Monica, CA 90405"
        },
        {
          "type": "p",
          "text": "Email: contact@thealtspot.com"
        },
        {
          "type": "p",
          "text": "Telephone: (310) 351-7347"
        },
        {
          "type": "p",
          "text": "SUBSCRIPTION AGREEMENT"
        },
        {
          "type": "p",
          "text": "This SUBSCRIPTION AGREEMENT (this “Subscription Agreement” or this “Agreement”) is entered into as of the date set forth on the signature page hereto (the “Subscription Date”), by and between ASC Simphonic II, LLC, a Delaware limited liability company (the “Company”), and the undersigned subscriber (the “Subscriber”)."
        },
        {
          "type": "p",
          "text": "Capitalized terms used and not otherwise defined in this Agreement shall have the meanings ascribed to such terms in the Memorandum or in the Operating Agreement of the Company, dated as of May 15, 2026 (as the same may be amended, supplemented, or restated from time to time, the “Operating Agreement”)."
        },
        {
          "type": "p",
          "text": "WHEREAS, the Company is a Delaware limited liability company formed for the sole purpose of acquiring and holding shares of Series B Preferred Stock (the “Series B Preferred”) of Simphonic, Inc., a Delaware corporation (“Simphonic”), together with associated warrants to purchase common stock of Simphonic (the “Warrants” and, together with the Series B Preferred, the “Portfolio Securities”);"
        },
        {
          "type": "p",
          "text": "WHEREAS, the Company is offering Class B Common Units (the “Class B Units” or the “Securities”) to a limited number of “accredited investors” as defined in Rule 501(a) of Regulation D promulgated under the Securities Act, in reliance on the exemption from registration provided by Section 4(a)(2) of the Securities Act and Rule 506 of Regulation D, and applicable state securities law exemptions (the “Offering”);"
        },
        {
          "type": "p",
          "text": "WHEREAS, AltSpot Capital, LLC serves as the Manager of the Company (the “Manager”); and"
        },
        {
          "type": "p",
          "text": "WHEREAS, the Subscriber wishes to subscribe for, and the Company wishes to issue and sell to the Subscriber, {{units}} Class B Units, on and subject to the terms and conditions of this Agreement and the Operating Agreement."
        },
        {
          "type": "p",
          "text": "NOW, THEREFORE, in consideration of the foregoing recitals and the mutual covenants and agreements contained herein, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the parties agree as follows:"
        }
      ],
      "panel": null
    },
    {
      "numeral": "1",
      "title": "SUBSCRIPTION",
      "blocks": [
        {
          "type": "section",
          "n": "1.1",
          "title": "Subscription",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "Subject to the terms and conditions of this Agreement, the Subscriber hereby irrevocably subscribes for and agrees to purchase {{units}} Class B Units (the “Subscribed Units”) at a price of $1.00 per Class B Unit (the “Per-Unit Price”), for an aggregate subscription amount equal to the Per-Unit Price multiplied by the number of Subscribed Units (the “Subscription Amount”). The Subscription Amount must be at least $50,000 (the “Minimum Subscription Amount”), provided that the Manager may, in its sole and absolute discretion, accept a Subscription Amount in a lesser amount."
        },
        {
          "type": "section",
          "n": "1.2",
          "title": "Acceptance; Closing",
          "text": "",
          "panel": 1
        },
        {
          "type": "p",
          "text": "This Agreement does not constitute an offer to sell or a solicitation of an offer to buy. The Subscriber’s subscription is not binding on the Company until this Agreement is accepted (the date of acceptance, the “Closing Date”) by, or on behalf of, the Company by execution of the signature page hereto, and the Subscriber’s admission as a Member is conditioned on the Subscriber’s execution of the counterpart signature page to the Operating Agreement attached hereto as Exhibit B. The Manager may accept or reject this subscription, in whole or in part, in its sole and absolute discretion. If this subscription is rejected, in whole or in part, the rejected portion of the Subscription Amount shall be returned promptly to the Subscriber without interest or deduction, and this Agreement shall (with respect to the rejected portion) be null and void."
        },
        {
          "type": "section",
          "n": "1.3",
          "title": "Funding",
          "text": "",
          "panel": 1
        },
        {
          "type": "p",
          "text": "Concurrently with the delivery of this Agreement, or otherwise as instructed by the Manager, the Subscriber shall pay the Subscription Amount in immediately available funds by wire transfer to the account designated by the Manager. The Manager may hold subscription funds in a non-interest-bearing account pending acceptance of this Agreement and the closing of the Offering. No interest will accrue or be payable on any subscription funds held by or for the Company."
        },
        {
          "type": "section",
          "n": "1.4",
          "title": "No Withdrawal",
          "text": "",
          "panel": 6
        },
        {
          "type": "p",
          "text": "The Subscriber’s offer to purchase the Subscribed Units is irrevocable, and the Subscriber may not withdraw, cancel, or revoke this Agreement once delivered, except as may be required by applicable law."
        },
        {
          "type": "section",
          "n": "1.5",
          "title": "Manager’s Right to Modify the Offering",
          "text": "",
          "panel": 1
        },
        {
          "type": "p",
          "text": "The Manager may, in its sole and absolute discretion: (a) modify, terminate, withdraw, or extend the Offering at any time; (b) conduct one or more closings of the Offering; (c) admit additional Members on such dates and on such terms as the Manager determines, subject to the Operating Agreement; and (d) waive or vary any of the conditions of the Offering with respect to one or more Subscribers."
        },
        {
          "type": "section",
          "n": "1.6",
          "title": "Conditional Subscription",
          "text": "",
          "panel": 1
        },
        {
          "type": "p",
          "text": "The Subscriber acknowledges that the Company’s acquisition of the Portfolio Securities is conditioned upon, among other things, the satisfaction or waiver of the conditions to closing set forth in the definitive transaction documents to be entered into between the Company and Simphonic. If such acquisition does not occur, or if the Manager determines, in its sole discretion, not to proceed with such acquisition, the Manager will return uninvested subscription funds to Subscribers (less any actual Company expenses incurred to date, to the extent provided in the Operating Agreement) without interest or deduction."
        }
      ],
      "panel": null
    },
    {
      "numeral": "2",
      "title": "RECEIPT AND REVIEW OF OFFERING DOCUMENTS",
      "blocks": [
        {
          "type": "p",
          "text": "The Subscriber hereby acknowledges and represents that:"
        },
        {
          "type": "item",
          "text": "The Subscriber has received, carefully reviewed, and understands this Agreement, the Memorandum, the Operating Agreement, and any other materials provided by the Manager in connection with the Offering (collectively, the “Offering Documents”), including without limitation the risk factors, conflicts of interest, and tax considerations described therein;"
        },
        {
          "type": "item",
          "text": "The Subscriber has had the opportunity to ask questions of, and receive answers from, the Manager and its representatives concerning the terms and conditions of the Offering, the Company, Simphonic, and the Portfolio Securities, and to obtain such additional information as the Subscriber has deemed necessary to verify the accuracy of the information furnished;"
        },
        {
          "type": "item",
          "text": "In making the decision to subscribe for the Subscribed Units, the Subscriber has relied solely on the Offering Documents and the Subscriber’s own independent investigation, due diligence, and analysis (and that of the Subscriber’s own advisors), and has not relied on any oral or written representation made by the Company, the Manager, or any of their respective affiliates, employees, agents, or representatives that is not contained in this Agreement or in the other Offering Documents;"
        },
        {
          "type": "item",
          "text": "The Subscriber has been advised to, and has had the opportunity to, consult with the Subscriber’s own attorney, accountant, and other financial and tax advisors regarding this investment and the Offering Documents;"
        },
        {
          "type": "item",
          "text": "The Subscriber acknowledges that the Memorandum is a summary of certain matters and is qualified in its entirety by the Operating Agreement and other definitive documents; in the event of any inconsistency between the Memorandum and the Operating Agreement, the Operating Agreement shall control;"
        },
        {
          "type": "item",
          "text": "The Subscriber acknowledges that no person has been authorized to make any representation or to provide any information other than as set forth in the Offering Documents, and the Subscriber has not relied on any such other representation or information; and"
        },
        {
          "type": "item",
          "text": "The Subscriber understands that, except as expressly set forth in the Offering Documents, the Company has not made and is not making any representation or warranty regarding Simphonic, its business, prospects, financial condition, results of operations, or the Portfolio Securities, and that information regarding Simphonic in the Offering Documents has not been independently verified by the Company or the Manager."
        }
      ],
      "panel": 1
    },
    {
      "numeral": "3",
      "title": "REPRESENTATIONS, WARRANTIES, AND COVENANTS OF THE SUBSCRIBER",
      "blocks": [
        {
          "type": "p",
          "text": "The Subscriber hereby represents, warrants, covenants, and agrees, as of the date hereof and as of the Closing Date (in each case as if made on and as of such date), as follows. These representations, warranties, and covenants are made in addition to (and not in limitation of) those set forth in Article 10 of the Operating Agreement, which the Subscriber will also make upon execution of the Operating Agreement counterpart signature page."
        },
        {
          "type": "section",
          "n": "3.1",
          "title": "Accredited Investor",
          "text": "",
          "panel": 2
        },
        {
          "type": "p",
          "text": "The Subscriber is an “accredited investor” as defined in Rule 501(a) of Regulation D promulgated under the Securities Act. The Subscriber’s accredited investor status is correctly indicated on the Accredited Investor Questionnaire attached hereto as Exhibit A, which is incorporated by reference into this Agreement and made a part hereof. All information provided by the Subscriber in the Accredited Investor Questionnaire is true, complete, and correct as of the date hereof and will be true, complete, and correct as of the Closing Date."
        },
        {
          "type": "section",
          "n": "3.2",
          "title": "Investment Intent",
          "text": "",
          "panel": 3
        },
        {
          "type": "p",
          "text": "The Subscriber is acquiring the Subscribed Units solely for the Subscriber’s own account, for investment purposes only, and not with a view to, or for resale in connection with, any distribution thereof, in whole or in part, in violation of the Securities Act or any applicable state securities laws. The Subscriber has no present intention of selling, granting any participation in, or otherwise distributing the Subscribed Units. The Subscriber does not have any contract, undertaking, agreement, or arrangement with any person to sell, transfer, grant a participation in, or otherwise distribute the Subscribed Units."
        },
        {
          "type": "section",
          "n": "3.3",
          "title": "Restricted Securities; No Registration",
          "text": "",
          "panel": 3
        },
        {
          "type": "p",
          "text": "The Subscriber understands that:"
        },
        {
          "type": "item",
          "text": "The Subscribed Units have not been, and will not be, registered under the Securities Act or qualified or registered under the securities laws of any state or other jurisdiction, in reliance on exemptions from such registration and qualification requirements, including the exemption provided by Section 4(a)(2) of the Securities Act and Rule 506 of Regulation D, and that the availability of such exemptions depends in part on the accuracy of the Subscriber’s representations herein;"
        },
        {
          "type": "item",
          "text": "The Subscribed Units constitute “restricted securities” within the meaning of Rule 144 under the Securities Act, and may not be resold, pledged, hypothecated, or otherwise transferred unless registered under the Securities Act and applicable state securities laws or pursuant to an available exemption from such registration and qualification requirements;"
        },
        {
          "type": "item",
          "text": "Neither the Company nor the Manager has any obligation to register or qualify the Subscribed Units under the Securities Act, any state securities laws, or any other law, or to assist the Subscriber in complying with any exemption from registration; and"
        },
        {
          "type": "item",
          "text": "The Subscribed Units may bear restrictive legends in accordance with the Operating Agreement and applicable law."
        },
        {
          "type": "section",
          "n": "3.4",
          "title": "Knowledge and Experience; Ability to Bear Risk",
          "text": "",
          "panel": 3
        },
        {
          "type": "p",
          "text": "The Subscriber, alone or together with the Subscriber’s advisors who are unaffiliated with and not compensated, directly or indirectly, by the Company or the Manager, has such knowledge and experience in financial, tax, and business matters as to be capable of evaluating the merits and risks of an investment in the Company. The Subscriber has the financial ability to bear the economic risk of an investment in the Company for an indefinite period of time, has adequate means of providing for the Subscriber’s current needs and contingencies, has no need for liquidity with respect to the investment in the Company, and can afford a complete loss of the Subscriber’s investment."
        },
        {
          "type": "section",
          "n": "3.5",
          "title": "Risk Factors; Speculative Investment",
          "text": "",
          "panel": 3
        },
        {
          "type": "p",
          "text": "The Subscriber acknowledges that:"
        },
        {
          "type": "item",
          "text": "An investment in the Subscribed Units is speculative and involves a high degree of risk, including the risk of total loss of the Subscriber’s investment;"
        },
        {
          "type": "item",
          "text": "The Company is a single-purpose investment vehicle whose sole investment will be in Simphonic, and accordingly the Subscriber will have no diversification within the Company;"
        },
        {
          "type": "item",
          "text": "The Company is newly organized and has no operating or financial history;"
        },
        {
          "type": "item",
          "text": "There is no public market for the Subscribed Units, and none is expected to develop, and the Subscribed Units are subject to substantial restrictions on transfer under the Operating Agreement, the Securities Act, and applicable state securities laws;"
        },
        {
          "type": "item",
          "text": "The Subscriber may be required, under certain circumstances described in the Operating Agreement (including Section 2.5), to make additional capital contributions to the Company, and a failure to do so may result in dilution of the Subscriber’s interest in the Company;"
        },
        {
          "type": "item",
          "text": "The Subscriber has carefully reviewed the risk factors set forth in the Memorandum, including but not limited to those relating to (a) the single-asset concentration in Simphonic, (b) the limited governance, voting, and information rights of Class B Members, (c) the limited fiduciary duties and broad indemnification of the Manager, (d) potential conflicts of interest involving the Manager and its affiliates (including ASC Simphonic LLC, an existing Series A holder of Simphonic), (e) the contingent and capped nature of the Revenue Participation Rights, (f) the time-limited nature of the Warrants, (g) U.S. federal, state, and local tax matters, including the Company’s intended election under Section 6226 of the Code (push-out election) and the Subscriber’s indemnification obligations under Section 7.4 of the Operating Agreement, (h) the early-stage nature of Simphonic and the healthcare regulatory and AI-related risks affecting Simphonic’s business, and (i) the mandatory binding arbitration in Los Angeles, California; and"
        },
        {
          "type": "item",
          "text": "The Subscriber has carefully evaluated such risk factors and is willing and able to bear the economic risks of, and a complete loss of, the Subscriber’s investment."
        },
        {
          "type": "section",
          "n": "3.6",
          "title": "Authority; No Conflicts",
          "text": "",
          "panel": 2
        },
        {
          "type": "p",
          "text": "The Subscriber, if a natural person, has reached the age of majority in the Subscriber’s jurisdiction of residence and has full power and legal capacity to execute this Agreement, the Accredited Investor Questionnaire, and the counterpart signature page to the Operating Agreement, and to perform the Subscriber’s obligations hereunder and thereunder. The Subscriber, if not a natural person, is duly organized, validly existing, and in good standing under the laws of its jurisdiction of formation, has full power and authority to execute and deliver this Agreement, the Accredited Investor Questionnaire, and the Operating Agreement, and to perform its obligations hereunder and thereunder, and has duly taken all action necessary to authorize such execution, delivery, and performance. The execution and delivery by the Subscriber of, and performance by the Subscriber of its obligations under, this Agreement, the Accredited Investor Questionnaire, and the Operating Agreement do not and will not (a) violate any law, regulation, judgment, or order applicable to the Subscriber, (b) violate or conflict with the Subscriber’s organizational documents (if applicable), or (c) violate, conflict with, result in a breach of, or constitute a default under any agreement to which the Subscriber is a party or by which the Subscriber is bound."
        },
        {
          "type": "section",
          "n": "3.7",
          "title": "Binding Obligation",
          "text": "",
          "panel": 2
        },
        {
          "type": "p",
          "text": "This Agreement, the Accredited Investor Questionnaire, and the Operating Agreement, when executed and delivered by the Subscriber, will constitute the legal, valid, and binding obligations of the Subscriber, enforceable against the Subscriber in accordance with their respective terms, except as enforceability may be limited by bankruptcy, insolvency, reorganization, or similar laws affecting creditors’ rights generally and by general equitable principles."
        },
        {
          "type": "section",
          "n": "3.8",
          "title": "Source of Funds",
          "text": "",
          "panel": 4
        },
        {
          "type": "p",
          "text": "The Subscription Amount and any subsequent capital contributions to be made by the Subscriber are derived from sources that are lawful and have not been derived directly or indirectly from any activity that contravenes any applicable laws or regulations, including any laws or regulations relating to anti-money laundering, anti-terrorism, anti-bribery and corruption, or sanctions. The Subscriber is not, nor is any beneficial owner, controlling person, principal, or affiliate of the Subscriber, (a) a person or entity named on the Specially Designated Nationals and Blocked Persons List or any other sanctions list maintained by the U.S. Department of the Treasury’s Office of Foreign Assets Control (“OFAC”), or (b) a person or entity organized or resident in any country or territory that is the subject of comprehensive sanctions administered by OFAC. The Subscriber agrees to provide such additional information and documentation as the Manager may reasonably request to comply with anti-money laundering, anti-terrorism, sanctions, and other similar laws and regulations."
        },
        {
          "type": "section",
          "n": "3.9",
          "title": "Accredited Investor Verification",
          "text": "",
          "panel": 2
        },
        {
          "type": "p",
          "text": "The Subscriber acknowledges that the Offering is being conducted in reliance on Rule 506(c) of Regulation D under the Securities Act and that the Company is required to take reasonable steps to verify the Subscriber’s status as an accredited investor. The Subscriber agrees to (a) complete accredited investor verification through iCapital (formerly Parallel Markets) or such other third-party verification service as the Manager may designate (the “Verification Service”), or (b) at the Manager’s option, deliver to the Manager a written confirmation, dated within the prior three (3) months, from a registered broker-dealer, registered investment adviser, licensed attorney, or certified public accountant, stating that such person has taken reasonable steps to verify the Subscriber’s accredited investor status and has determined that the Subscriber is an accredited investor. The Subscriber authorizes the Verification Service to share the results of such verification with the Manager and the Company, and the Subscriber agrees to provide such additional information and documentation as the Verification Service or the Manager may reasonably request to complete the verification. The Subscriber acknowledges that the Manager may decline to accept the Subscriber’s subscription if accredited investor status cannot be verified to the Manager’s reasonable satisfaction in accordance with Rule 506(c)."
        },
        {
          "type": "section",
          "n": "3.10",
          "title": "Pre-Existing Relationship; Investment Experience",
          "text": "",
          "panel": 2
        },
        {
          "type": "p",
          "text": "Either (a) the Subscriber has a preexisting personal or business relationship with the Company, the Manager, or one or more of the Manager’s control persons, or (b) by reason of the Subscriber’s business or financial experience (or that of the Subscriber’s financial advisor who is unaffiliated with, and not compensated by, the Company or the Manager), the Subscriber is capable of evaluating the risks and merits of an investment in the Subscribed Units and of protecting the Subscriber’s own interests in connection with this investment."
        },
        {
          "type": "section",
          "n": "3.11",
          "title": "Tax Matters",
          "text": "",
          "panel": 4
        },
        {
          "type": "p",
          "text": "The Subscriber understands that:"
        },
        {
          "type": "item",
          "text": "The U.S. federal, state, local, and non-U.S. tax consequences of an investment in the Company are complex and uncertain;"
        },
        {
          "type": "item",
          "text": "The Company will be classified as a partnership for U.S. federal income tax purposes, and the Subscriber will be required to take into account the Subscriber’s allocable share of the Company’s items of income, gain, loss, deduction, and credit, regardless of whether the Company makes any distributions in any particular year;"
        },
        {
          "type": "item",
          "text": "The Company intends to elect the application of Section 6226 of the Code (push-out election), as set forth in Section 7.4 of the Operating Agreement, and accordingly any IRS adjustments to the Company’s items of income or deduction may be allocated to the Subscriber for the reviewed year;"
        },
        {
          "type": "item",
          "text": "Pursuant to Section 7.4 of the Operating Agreement, the Subscriber is required to provide the Tax Representative with such tax information, documents, certifications, tax identification numbers, and tax forms as the Tax Representative may request, and to indemnify the Company, the Manager, and the Tax Representative against tax liabilities resulting from the Subscriber’s failure to comply;"
        },
        {
          "type": "item",
          "text": "The Subscriber will be responsible for the Subscriber’s own tax liabilities (subject to any Tax Distributions under Section 5.6 of the Operating Agreement);"
        },
        {
          "type": "item",
          "text": "None of the Company, the Manager, the other Members, nor their respective affiliates, employees, agents, or representatives will be responsible or liable for the tax consequences to the Subscriber of an investment in the Company;"
        },
        {
          "type": "item",
          "text": "The Subscriber is relying solely on the Subscriber’s own advisors with respect to the tax consequences of this investment; and"
        },
        {
          "type": "item",
          "text": "The Subscriber acknowledges that there can be no assurance that the Code or the Treasury Regulations will not be amended or interpreted in the future in a manner that adversely affects the Subscriber."
        },
        {
          "type": "section",
          "n": "3.12",
          "title": "ERISA Status",
          "text": "",
          "panel": 4
        },
        {
          "type": "p",
          "text": "The Subscriber represents and warrants that the Subscriber is, or is not, a “benefit plan investor” within the meaning of Section 3(42) of ERISA and the U.S. Department of Labor’s plan asset regulations (a “Benefit Plan Investor”), as indicated by the Subscriber’s response on the Accredited Investor Questionnaire. If the Subscriber is a Benefit Plan Investor, the Subscriber further represents and warrants that the Subscriber’s investment in the Company has been duly authorized and is in compliance with all applicable provisions of ERISA and the Code, and that the fiduciary causing the Subscriber to make this investment has determined that the investment is appropriate for the Benefit Plan Investor."
        },
        {
          "type": "section",
          "n": "3.13",
          "title": "Confidentiality",
          "text": "",
          "panel": 6
        },
        {
          "type": "p",
          "text": "The Subscriber acknowledges that the Memorandum and the other Offering Documents have been furnished to the Subscriber on a confidential basis. The Subscriber will not, without the prior written consent of the Manager, reproduce, distribute, disclose, or use the Memorandum or any other Offering Document, or any portion thereof or information contained therein, except that the Subscriber may disclose such information (a) to the Subscriber’s legal, tax, financial, and other professional advisors who have a need to know such information for the purpose of evaluating the Subscriber’s investment and who are bound by obligations of confidentiality, and (b) as required by applicable law, regulation, or legal process, in which case the Subscriber will, to the extent legally permissible, promptly notify the Manager prior to disclosure."
        },
        {
          "type": "section",
          "n": "3.14",
          "title": "Updates to Information",
          "text": "",
          "panel": 6
        },
        {
          "type": "p",
          "text": "The Subscriber will promptly notify the Manager in writing if any of the representations or warranties made by the Subscriber in this Agreement or in the Accredited Investor Questionnaire becomes inaccurate or incomplete in any material respect at any time prior to the Closing Date or thereafter. Until expressly notified by the Subscriber to the contrary, the Manager and the Company may rely on the representations, warranties, and information provided by the Subscriber as continuing to be true, complete, and correct."
        },
        {
          "type": "section",
          "n": "3.15",
          "title": "Survival",
          "text": "",
          "panel": 6
        },
        {
          "type": "p",
          "text": "All representations, warranties, covenants, and agreements made by the Subscriber in this Agreement, the Accredited Investor Questionnaire, and the Operating Agreement shall survive the execution and delivery of this Agreement, the acceptance of the Subscriber’s subscription, the Closing Date, and the dissolution of the Company."
        }
      ],
      "panel": null
    },
    {
      "numeral": "4",
      "title": "OPERATING AGREEMENT",
      "blocks": [
        {
          "type": "section",
          "n": "4.1",
          "title": "Counterpart Signature; Admission as Member",
          "text": "",
          "panel": 5
        },
        {
          "type": "p",
          "text": "By executing this Agreement and the counterpart signature page to the Operating Agreement attached hereto as Exhibit B, the Subscriber agrees to become a Member of the Company, to be bound by all of the terms and conditions of the Operating Agreement, and to make the representations, warranties, and covenants set forth in Article 10 of the Operating Agreement. Upon acceptance of this Agreement by the Manager and execution by the Manager of the counterpart signature page to the Operating Agreement, the Subscriber shall be admitted as a Member of the Company holding {{units}} Class B Units, and Exhibit A to the Operating Agreement shall be amended to reflect the Subscriber’s admission, capital contribution, and Percentage Interest."
        },
        {
          "type": "section",
          "n": "4.2",
          "title": "Power of Attorney",
          "text": "",
          "panel": 5
        },
        {
          "type": "p",
          "text": "The Subscriber hereby irrevocably constitutes and appoints the Manager (and each authorized officer, agent, or attorney-in-fact thereof) as the Subscriber’s true and lawful attorney-in-fact, with full power of substitution and resubstitution, in the Subscriber’s name, place, and stead, to make, execute, sign, acknowledge, swear to, deliver, file, and record (a) the Operating Agreement (and any amendments and restatements thereto effected in accordance with its terms), (b) any amendments to Exhibit A or Schedule I to the Operating Agreement to reflect the admission, withdrawal, capital contribution, distribution, or Percentage Interest of any Member (including the Subscriber), (c) all certificates and other instruments deemed advisable by the Manager to qualify or continue the Company as a limited liability company in any jurisdiction in which the Company conducts business, (d) all instruments that effect a change or modification of the Company in accordance with the Operating Agreement, and (e) all instruments necessary or appropriate to dissolve and liquidate the Company in accordance with the Operating Agreement. This power of attorney is coupled with an interest, is irrevocable, and shall survive the death, incapacity, dissolution, bankruptcy, or disability of the Subscriber."
        },
        {
          "type": "section",
          "n": "4.3",
          "title": "Acknowledgment of Manager Authority",
          "text": "",
          "panel": 5
        },
        {
          "type": "p",
          "text": "The Subscriber acknowledges and agrees that the Manager has full, complete, and exclusive authority, power, and discretion to manage and control the business, property, and affairs of the Company in accordance with the Operating Agreement, including with respect to (a) the negotiation, execution, and performance of the definitive transaction documents with Simphonic, (b) the voting, sale, exercise, and other disposition of the Portfolio Securities (including the Warrants), (c) responses to drag-along, tag-along, pre-emptive, right-of-first-refusal, and other similar provisions in Simphonic’s organizational documents and shareholder agreements, (d) tax matters and elections, including elections under Sections 6221(b) and 6226 of the Code, (e) capital calls, distributions, and admission of additional Members, and (f) all other matters relating to the operation of the Company. The Subscriber further acknowledges that, except as expressly provided in the Operating Agreement, Class B Units have no voting rights and Class B Members have no right to participate in management of the Company."
        }
      ],
      "panel": null
    },
    {
      "numeral": "5",
      "title": "INDEMNIFICATION",
      "blocks": [
        {
          "type": "p",
          "text": "The Subscriber agrees to indemnify and hold harmless the Company, the Manager, and each of their respective members, managers, officers, directors, employees, agents, affiliates, advisors, and representatives (each, an “Indemnified Party”) from and against any and all losses, claims, damages, liabilities, costs, and expenses (including reasonable attorneys’ fees and disbursements) arising out of or relating to:"
        },
        {
          "type": "item",
          "text": "Any breach by the Subscriber of any representation, warranty, covenant, or agreement made by the Subscriber in this Agreement, the Accredited Investor Questionnaire, or the Operating Agreement;"
        },
        {
          "type": "item",
          "text": "Any inaccuracy or omission in any information provided by the Subscriber to the Company or the Manager;"
        },
        {
          "type": "item",
          "text": "Any disposition of any Subscribed Units by the Subscriber in violation of this Agreement, the Operating Agreement, or applicable law; and"
        },
        {
          "type": "item",
          "text": "Any tax liabilities of the Company arising as a result of the Subscriber’s failure to comply with Sections 7.4.2 and 7.4.3 of the Operating Agreement (including failure to provide tax information requested by the Tax Representative or to report adjustments allocated to the Subscriber under Section 6226 of the Code)."
        },
        {
          "type": "p",
          "text": "The Subscriber’s indemnification obligations under this Section 5 shall be in addition to, and not in limitation of, the Subscriber’s indemnification obligations under the Operating Agreement (including under Section 7.4 thereof) and shall survive the dissolution of the Company and any transfer or assignment of the Subscriber’s Units."
        }
      ],
      "panel": 6
    },
    {
      "numeral": "6",
      "title": "MISCELLANEOUS",
      "blocks": [
        {
          "type": "section",
          "n": "6.1",
          "title": "Governing Law",
          "text": "",
          "panel": 5
        },
        {
          "type": "p",
          "text": "This Agreement shall be governed by, and construed and enforced in accordance with, the laws of the State of Delaware, without regard to any conflicts-of-laws principles that would require the application of the laws of any other jurisdiction."
        },
        {
          "type": "section",
          "n": "6.2",
          "title": "Arbitration; Waiver of Jury Trial",
          "text": "",
          "panel": 6
        },
        {
          "type": "p",
          "text": "Any controversy or claim arising out of or relating to this Agreement (other than any claim for which equitable relief is sought to enforce the confidentiality, transfer, or similar provisions of this Agreement or the Operating Agreement) shall be resolved by binding, non-appealable arbitration before the American Arbitration Association in Los Angeles, California, in accordance with Section 11.4 of the Operating Agreement. THE SUBSCRIBER HEREBY KNOWINGLY, VOLUNTARILY, AND INTENTIONALLY WAIVES, TO THE FULLEST EXTENT PERMITTED BY LAW, ANY RIGHT THE SUBSCRIBER MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY LITIGATION ARISING OUT OF, UNDER, OR IN CONNECTION WITH THIS AGREEMENT."
        },
        {
          "type": "section",
          "n": "6.3",
          "title": "Notices",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "All notices, requests, demands, and other communications under this Agreement shall be in writing (including by electronic mail) and shall be deemed to have been duly given and received when delivered to the address or email address specified by the recipient on the signature page hereto (or as otherwise designated by the recipient by notice given in accordance with this Section 6.3)."
        },
        {
          "type": "section",
          "n": "6.4",
          "title": "Entire Agreement",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "This Agreement (including the Exhibits hereto), together with the Operating Agreement, constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior agreements, understandings, negotiations, and discussions, whether oral or written, with respect to such subject matter. To the extent any provision of this Agreement conflicts with any provision of the Operating Agreement, the Operating Agreement shall control."
        },
        {
          "type": "section",
          "n": "6.5",
          "title": "Amendments",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "This Agreement may not be amended, modified, or supplemented except by a written instrument signed by each of the parties hereto."
        },
        {
          "type": "section",
          "n": "6.6",
          "title": "Assignment",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "This Agreement may not be assigned by the Subscriber without the prior written consent of the Manager, which consent may be granted or withheld in the Manager’s sole and absolute discretion. Any purported assignment in violation of this Section 6.6 shall be null and void. Subject to the foregoing, this Agreement shall be binding upon and inure to the benefit of the parties hereto and their respective successors, heirs, executors, administrators, legal representatives, and permitted assigns."
        },
        {
          "type": "section",
          "n": "6.7",
          "title": "No Third-Party Beneficiaries",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "Except as expressly set forth herein with respect to Indemnified Parties, this Agreement is for the sole benefit of the parties hereto and their respective successors and permitted assigns, and nothing herein, express or implied, is intended to or shall confer upon any other person any legal or equitable right, benefit, or remedy of any nature whatsoever under or by reason of this Agreement."
        },
        {
          "type": "section",
          "n": "6.8",
          "title": "Severability",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "If any provision of this Agreement is held to be invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other provision of this Agreement or invalidate or render unenforceable such provision in any other jurisdiction, and this Agreement shall be reformed, construed, and enforced in such jurisdiction so as to best give effect to the parties’ intent."
        },
        {
          "type": "section",
          "n": "6.9",
          "title": "Counterparts; Electronic Signatures",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "This Agreement may be executed in two or more counterparts, each of which shall be deemed an original and all of which together shall constitute one and the same instrument. Counterparts may be delivered by facsimile, electronic mail (including PDF or other imaged file), or other electronic means (including DocuSign or any other electronic signature method that complies with the U.S. federal ESIGN Act of 2000), and a counterpart so delivered shall be deemed valid, binding, and effective for all purposes."
        },
        {
          "type": "section",
          "n": "6.10",
          "title": "Headings",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "The headings of the sections of this Agreement are for convenience of reference only and shall not affect the interpretation or construction of any provision of this Agreement."
        },
        {
          "type": "section",
          "n": "6.11",
          "title": "Construction",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "This Agreement has been negotiated by the parties with the advice of counsel and shall not be construed against the drafter. Each reference to “including” shall be deemed to mean “including without limitation.” Each reference to a particular gender shall be deemed to include each other gender, and each reference to the singular shall be deemed to include the plural and vice versa."
        },
        {
          "type": "section",
          "n": "6.12",
          "title": "Further Assurances",
          "text": "",
          "panel": null
        },
        {
          "type": "p",
          "text": "The Subscriber agrees to execute and deliver such additional documents, instruments, and certificates, and to take such additional actions, as the Manager may reasonably request in order to give effect to the provisions of this Agreement and to consummate the transactions contemplated hereby."
        },
        {
          "type": "p",
          "text": "[Signature page follows]"
        },
        {
          "type": "p",
          "text": "SIGNATURE PAGE TO SUBSCRIPTION AGREEMENT"
        },
        {
          "type": "p",
          "text": "ASC SIMPHONIC II, LLC"
        },
        {
          "type": "p",
          "text": "IN WITNESS WHEREOF, the undersigned Subscriber has executed this Subscription Agreement as of the Subscription Date set forth below."
        },
        {
          "type": "p",
          "text": "SUBSCRIPTION SUMMARY"
        },
        {
          "type": "p",
          "text": "Subscription Amount",
          "mergeValue": "{{amount}}"
        },
        {
          "type": "p",
          "text": "$________________________"
        },
        {
          "type": "p",
          "text": "Number of Class B Units (at $1.00/Unit)"
        },
        {
          "type": "p",
          "text": "________________________ Units"
        },
        {
          "type": "p",
          "text": "Subscription Date",
          "mergeValue": "{{date}}"
        },
        {
          "type": "p",
          "text": "________________________, 2026"
        },
        {
          "type": "p",
          "text": "Indicate the form of Subscriber by checking the applicable box:"
        },
        {
          "type": "p",
          "text": "[ ] Individual"
        },
        {
          "type": "p",
          "text": "[ ] Joint with Spouse / Joint Tenants"
        },
        {
          "type": "p",
          "text": "[ ] Trust"
        },
        {
          "type": "p",
          "text": "[ ] Corporation"
        },
        {
          "type": "p",
          "text": "[ ] Limited Liability Company"
        },
        {
          "type": "p",
          "text": "[ ] Partnership"
        },
        {
          "type": "p",
          "text": "[ ] Individual Retirement Account / Other Retirement Plan"
        },
        {
          "type": "p",
          "text": "[ ] Other (please specify): __________________________________"
        },
        {
          "type": "p",
          "text": "FOR INDIVIDUAL SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Signature: {{signature}}"
        },
        {
          "type": "p",
          "text": "Print Name (Joint Subscriber, if any): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Signature (Joint Subscriber, if any): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "FOR ENTITY SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Name of Entity: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Jurisdiction of Formation: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Type of Entity: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Tax Identification Number: _______________________________________________"
        },
        {
          "type": "p",
          "text": "By: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Print Name of Authorized Signatory: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Title: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "SUBSCRIBER CONTACT INFORMATION:"
        },
        {
          "type": "p",
          "text": "Mailing Address: _______________________________________________"
        },
        {
          "type": "p",
          "text": "City, State, Postal Code: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Country: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Telephone: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Email Address: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Tax Identification / Social Security Number: _______________________________________________"
        },
        {
          "type": "p",
          "text": "State / Country of Residence (or Principal Place of Business): _______________________________________________"
        },
        {
          "type": "p",
          "text": "ACCEPTED BY THE COMPANY"
        },
        {
          "type": "p",
          "text": "The Company hereby accepts the foregoing subscription, in whole or in the amount indicated below, on the Closing Date set forth below."
        },
        {
          "type": "p",
          "text": "Subscription Amount Accepted: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Number of Class B Units Issued: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Closing Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "ASC SIMPHONIC II, LLC"
        },
        {
          "type": "p",
          "text": "By: AltSpot Capital, LLC, its Manager"
        },
        {
          "type": "p",
          "text": "By: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Title: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        }
      ],
      "panel": null
    },
    {
      "numeral": "EXHIBIT A",
      "title": "EXHIBIT A",
      "blocks": [
        {
          "type": "p",
          "text": "ACCREDITED INVESTOR QUESTIONNAIRE"
        },
        {
          "type": "p",
          "text": "Purpose of Questionnaire"
        },
        {
          "type": "p",
          "text": "This Accredited Investor Questionnaire (this “Questionnaire”) is being furnished to you in connection with the offer and sale by ASC Simphonic II, LLC (the “Company”) of Class B Common Units (the “Securities”) to qualify the offer and sale of the Securities for an exemption from registration under the U.S. Securities Act of 1933, as amended (the “Securities Act”), pursuant to Section 4(a)(2) thereof and Rule 506 of Regulation D promulgated thereunder, and from registration under applicable state securities laws."
        },
        {
          "type": "p",
          "text": "To establish the availability of these exemptions, the Company is required to confirm that each prospective investor is an “accredited investor” within the meaning of Rule 501(a) of Regulation D under the Securities Act. Your responses to this Questionnaire will be relied upon for purposes of confirming your accredited investor status. The information you provide in this Questionnaire will be treated confidentially, except that the Company and the Manager may present this Questionnaire to such persons as they deem appropriate to establish the availability of exemptions from registration under federal and state securities laws."
        },
        {
          "type": "p",
          "text": "PLEASE COMPLETE, EXECUTE, AND RETURN THIS QUESTIONNAIRE TOGETHER WITH YOUR SUBSCRIPTION AGREEMENT. PLEASE ANSWER EACH QUESTION TRUTHFULLY AND COMPLETELY. IF AN ANSWER IS “NONE” OR “NOT APPLICABLE,” PLEASE SO INDICATE."
        },
        {
          "type": "p",
          "text": "Part I — Subscriber Identification"
        },
        {
          "type": "p",
          "text": "Name of Subscriber: _______________________________________________"
        },
        {
          "type": "p",
          "text": "(If joint, name of Joint Subscriber): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Type of Subscriber (individual, trust, LLC, etc.): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Jurisdiction of Formation/Residence: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Tax Identification / Social Security Number: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Mailing Address: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Telephone: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Email Address: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Part II — Accredited Investor Status"
        },
        {
          "type": "p",
          "text": "Please review the categories below and check each box that applies to you. You must check at least one box to qualify as an accredited investor. If none of the categories applies, you are not an accredited investor and will not be permitted to subscribe for the Securities."
        },
        {
          "type": "p",
          "text": "A. Natural Persons"
        },
        {
          "type": "p",
          "text": "If the Subscriber is a natural person (or a natural person and the Subscriber’s spouse, jointly), the Subscriber qualifies as an accredited investor if any of the following is true:"
        },
        {
          "type": "p",
          "text": "[ ] (1) Net Worth Test. The Subscriber’s individual net worth, or joint net worth with the Subscriber’s spouse or spousal equivalent, exceeds $1,000,000 at the time of subscription. For purposes of this calculation, (a) “spousal equivalent” means a cohabitant occupying a relationship generally equivalent to that of a spouse; (b) the value of the Subscriber’s primary residence is not included in the calculation of net worth, and indebtedness secured by the primary residence (up to its estimated fair market value) is not included as a liability, except that any incremental amount of indebtedness incurred in the 60 days preceding subscription (other than as a result of the acquisition of the primary residence) is included as a liability, and any indebtedness in excess of the fair market value of the primary residence is included as a liability."
        },
        {
          "type": "p",
          "text": "[ ] (2) Income Test. The Subscriber had individual income in excess of $200,000 in each of the two most recent calendar years (or joint income with the Subscriber’s spouse or spousal equivalent in excess of $300,000 in each of those years), and reasonably expects to reach the same income level in the current calendar year."
        },
        {
          "type": "p",
          "text": "[ ] (3) Professional Certifications. The Subscriber holds, in good standing, one of the following professional certifications, designations, or credentials: a Series 7 (General Securities Representative) license, a Series 65 (Investment Adviser Representative) license, or a Series 82 (Private Securities Offerings Representative) license. The Subscriber will provide evidence of the same upon request."
        },
        {
          "type": "p",
          "text": "[ ] (4) Knowledgeable Employee. The Subscriber is a “knowledgeable employee,” as defined in Rule 3c-5(a)(4) under the Investment Company Act of 1940, of the issuer of the Securities (where the issuer would be an investment company but for the exclusion provided by Section 3(c)(1) or 3(c)(7) of the Investment Company Act). [Note: This category is generally not available for the Company; included for completeness.]"
        },
        {
          "type": "p",
          "text": "[ ] (5) Family Client. The Subscriber is a “family client”, as defined in Rule 202(a)(11)(G)-1 under the Investment Advisers Act of 1940, of a family office that itself qualifies as an accredited investor under category B(11) below, whose investment in the Company is directed by such family office."
        },
        {
          "type": "p",
          "text": "B. Entities"
        },
        {
          "type": "p",
          "text": "If the Subscriber is not a natural person, the Subscriber qualifies as an accredited investor if any of the following is true:"
        },
        {
          "type": "p",
          "text": "[ ] (1) $5 Million Total Assets Entity. The Subscriber is an entity (including a corporation, partnership, limited liability company, business trust, or organization described in Section 501(c)(3) of the Internal Revenue Code) not formed for the specific purpose of acquiring the Securities and having total assets in excess of $5,000,000."
        },
        {
          "type": "p",
          "text": "[ ] (2) Bank, Savings & Loan, or Insurance Company. The Subscriber is a bank as defined in Section 3(a)(2) of the Securities Act, or a savings and loan association or other institution as defined in Section 3(a)(5)(A) of the Securities Act, whether acting in its individual or fiduciary capacity; an insurance company as defined in Section 2(a)(13) of the Securities Act; or a registered broker-dealer or investment adviser."
        },
        {
          "type": "p",
          "text": "[ ] (3) Investment Company / BDC / SBIC / RBIC. The Subscriber is an investment company registered under the Investment Company Act of 1940, a business development company as defined in Section 2(a)(48) of that Act, a Small Business Investment Company licensed by the U.S. Small Business Administration under Section 301(c) or (d) of the Small Business Investment Act of 1958, or a Rural Business Investment Company as defined in Section 384A of the Consolidated Farm and Rural Development Act."
        },
        {
          "type": "p",
          "text": "[ ] (4) Plan Established by State or Political Subdivision. The Subscriber is a plan established and maintained by a state, its political subdivisions, or any agency or instrumentality thereof, for the benefit of its employees, with total assets in excess of $5,000,000."
        },
        {
          "type": "p",
          "text": "[ ] (5) Employee Benefit Plan. The Subscriber is an employee benefit plan within the meaning of ERISA: (i) for which the investment decision is made by a plan fiduciary that is a bank, insurance company, or registered investment adviser; or (ii) with total assets in excess of $5,000,000; or (iii) that is a self-directed plan with investment decisions made solely by persons that are accredited investors."
        },
        {
          "type": "p",
          "text": "[ ] (6) Private Business Development Company. The Subscriber is a “private business development company” as defined in Section 202(a)(22) of the Investment Advisers Act of 1940."
        },
        {
          "type": "p",
          "text": "[ ] (7) All-Accredited Entity. The Subscriber is an entity all of whose equity owners are accredited investors. (If checked, please be prepared to provide accredited-investor confirmations from each equity owner upon request.)"
        },
        {
          "type": "p",
          "text": "[ ] (8) Trust ($5M / Sophisticated Trustee). The Subscriber is a trust with total assets in excess of $5,000,000, that was not formed for the specific purpose of acquiring the Securities, and whose purchase is directed by a person who has such knowledge and experience in financial and business matters that such person is capable of evaluating the merits and risks of the prospective investment."
        },
        {
          "type": "p",
          "text": "[ ] (9) Revocable Grantor Trust. The Subscriber is a revocable trust that may be amended or revoked at any time by the grantors thereof, and all of the grantors are accredited investors. (Each grantor must complete a separate Questionnaire.)"
        },
        {
          "type": "p",
          "text": "[ ] (10) Investments-Based Entity ($5M Investments). The Subscriber is an entity, of a type not listed in any other category, not formed for the specific purpose of acquiring the Securities, and owning “investments” (as defined in Rule 2a51-1(b) under the Investment Company Act of 1940) in excess of $5,000,000."
        },
        {
          "type": "p",
          "text": "[ ] (11) Family Office. The Subscriber is a “family office,” as defined in Rule 202(a)(11)(G)-1 under the Investment Advisers Act of 1940, that (a) has assets under management in excess of $5,000,000, (b) was not formed for the specific purpose of acquiring the Securities, and (c) whose prospective investment is directed by a person who has such knowledge and experience in financial and business matters that such family office is capable of evaluating the merits and risks of the prospective investment."
        },
        {
          "type": "p",
          "text": "[ ] (12) Family Client of a Family Office. The Subscriber is a “family client,” as defined in Rule 202(a)(11)(G)-1 under the Investment Advisers Act of 1940, of a family office described in B(11) above, whose prospective investment in the Company is directed by such family office."
        },
        {
          "type": "p",
          "text": "If the Subscriber checked Box B(7) (All-Accredited Entity) or B(9) (Revocable Grantor Trust), the Subscriber agrees to provide the Manager with such additional information as the Manager may reasonably request to confirm the accredited investor status of each equity owner or grantor, as applicable."
        },
        {
          "type": "p",
          "text": "Part III — Verification of Accredited Investor Status"
        },
        {
          "type": "p",
          "text": "Note: This Part III is required because the Company is conducting the Offering under Rule 506(c) of Regulation D, which permits general solicitation but requires the Company to take reasonable steps to verify the Subscriber’s accredited investor status."
        },
        {
          "type": "p",
          "text": "If applicable, please indicate the method by which the Subscriber wishes to verify accredited investor status:"
        },
        {
          "type": "p",
          "text": "[ ] (1) Income Verification. The Subscriber will provide copies of any IRS Form W-2, Form 1099, Schedule K-1, or Form 1040 (or any other applicable form) for the two most recent years showing income meeting the thresholds in Part II.A(2), together with a written representation that the Subscriber has a reasonable expectation of reaching the same level in the current year."
        },
        {
          "type": "p",
          "text": "[ ] (2) Net Worth Verification. The Subscriber will provide, dated within the prior three months, (i) for assets: bank statements, brokerage statements, securities holdings statements, certificates of deposit, tax assessments, and appraisal reports, and (ii) for liabilities: a consumer credit report from at least one of the nationwide consumer reporting agencies."
        },
        {
          "type": "p",
          "text": "[ ] (3) Professional Letter. The Subscriber will provide a written confirmation, dated within the prior three months, from a registered broker-dealer, registered investment adviser, licensed attorney, or certified public accountant, stating that such person has taken reasonable steps to verify the Subscriber’s accredited investor status within the prior three months and has determined that the Subscriber is an accredited investor."
        },
        {
          "type": "p",
          "text": "[ ] (4) Third-Party Verification Service. The Subscriber will complete accredited investor verification through iCapital (formerly Parallel Markets) or such other third-party verification service as the Manager may designate, and will authorize the verification service to share the results of such verification with the Manager and the Company."
        },
        {
          "type": "p",
          "text": "[ ] (5) Other. _______________________________________________"
        },
        {
          "type": "p",
          "text": "Part IV — ERISA and Plan Asset Status"
        },
        {
          "type": "p",
          "text": "The Subscriber represents and warrants that the Subscriber is or is not a Benefit Plan Investor (as defined below). Please check the applicable box."
        },
        {
          "type": "p",
          "text": "[ ] (1) The Subscriber IS NOT a Benefit Plan Investor."
        },
        {
          "type": "p",
          "text": "[ ] (2) The Subscriber IS a Benefit Plan Investor. Please specify type below."
        },
        {
          "type": "p",
          "text": "If the Subscriber is a Benefit Plan Investor, please indicate the type:"
        },
        {
          "type": "p",
          "text": "[ ] Employee benefit plan subject to Title I of ERISA"
        },
        {
          "type": "p",
          "text": "[ ] Plan subject to Section 4975 of the Internal Revenue Code (e.g., individual retirement account)"
        },
        {
          "type": "p",
          "text": "[ ] Entity whose underlying assets include “plan assets” within the meaning of ERISA by reason of investment by employee benefit plans subject to Title I of ERISA or plans subject to Section 4975 of the Code"
        },
        {
          "type": "p",
          "text": "“Benefit Plan Investor” means (i) any employee benefit plan subject to Title I of ERISA; (ii) any plan to which Section 4975 of the Code applies; and (iii) any entity whose underlying assets include “plan assets” by reason of any such plan’s investment in the entity (within the meaning of ERISA Section 3(42) and 29 C.F.R. Section 2510.3-101)."
        },
        {
          "type": "p",
          "text": "If the Subscriber is a Benefit Plan Investor, the Subscriber further represents that:"
        },
        {
          "type": "item",
          "text": "The fiduciary directing the investment in the Company has determined that the investment is consistent with applicable fiduciary obligations under ERISA and the Code, and is appropriate for the plan in light of its risk, liquidity, diversification, and other investment objectives;"
        },
        {
          "type": "item",
          "text": "The investment in the Company will not constitute a non-exempt prohibited transaction under ERISA Section 406 or Code Section 4975; and"
        },
        {
          "type": "item",
          "text": "The Subscriber acknowledges that the Manager intends to monitor and limit investment in the Company by Benefit Plan Investors so that participation by such investors does not equal or exceed 25% of the value of any class of equity interests in the Company (or to otherwise rely on an applicable exception under the U.S. Department of Labor’s plan asset regulations), and that the Manager may reject or limit subscriptions from Benefit Plan Investors in order to prevent the Company’s assets from being treated as “plan assets.”"
        },
        {
          "type": "p",
          "text": "Part V — “Bad Actor” Disqualifying Events (Rule 506(d))"
        },
        {
          "type": "p",
          "text": "Rule 506(d) of Regulation D under the Securities Act prohibits the offer and sale of securities under Rule 506 if any “covered person” (which includes, with respect to the Subscriber, any beneficial owner of 20% or more of the issuer’s outstanding voting equity securities, calculated on the basis of voting power) is subject to certain enumerated disqualifying events. The Manager is required to confirm that no Subscriber, if such Subscriber would beneficially own 20% or more of the Company’s voting equity securities, is subject to any such disqualifying event."
        },
        {
          "type": "p",
          "text": "If the Subscriber’s subscription would result in the Subscriber beneficially owning 20% or more of the Company’s outstanding voting equity securities (calculated on the basis of voting power), the Subscriber represents and warrants that, to the Subscriber’s knowledge, neither the Subscriber nor any beneficial owner, control person, principal, or affiliate of the Subscriber:"
        },
        {
          "type": "item",
          "text": "Has been convicted, within ten (10) years of the date of this Questionnaire (or five (5) years in the case of issuers, their predecessors and affiliated issuers), of any felony or misdemeanor (a) in connection with the purchase or sale of any security, (b) involving the making of any false filing with the SEC, or (c) arising out of the conduct of the business of an underwriter, broker, dealer, municipal securities dealer, investment adviser, or paid solicitor of purchasers of securities;"
        },
        {
          "type": "item",
          "text": "Is subject to any order, judgment, or decree of any court of competent jurisdiction, entered within five (5) years of the date of this Questionnaire, that, at the time of subscription, restrains or enjoins such person from engaging or continuing to engage in any conduct or practice (a) in connection with the purchase or sale of any security, (b) involving the making of any false filing with the SEC, or (c) arising out of the conduct of the business of an underwriter, broker, dealer, municipal securities dealer, investment adviser, or paid solicitor of purchasers of securities;"
        },
        {
          "type": "item",
          "text": "Is subject to a final order of a state securities commission (or an agency or officer of a state performing like functions); a state authority that supervises or examines banks, savings associations, or credit unions; a state insurance commission (or an agency or officer of a state performing like functions); an appropriate federal banking agency; the U.S. Commodity Futures Trading Commission; or the National Credit Union Administration that (a) bars the person from association with an entity regulated by such commission, authority, agency, or officer, from engaging in the business of securities, insurance, or banking, or from engaging in savings association or credit union activities; or (b) constitutes a final order based on a violation of any law or regulation that prohibits fraudulent, manipulative, or deceptive conduct entered within ten (10) years of the date of this Questionnaire;"
        },
        {
          "type": "item",
          "text": "Is subject to an order of the SEC entered pursuant to Section 15(b) or 15B(c) of the Securities Exchange Act of 1934 or Section 203(e) or (f) of the Investment Advisers Act of 1940 that, at the time of subscription, (a) suspends or revokes such person’s registration as a broker, dealer, municipal securities dealer, or investment adviser; (b) places limitations on the activities, functions, or operations of such person; or (c) bars such person from being associated with any entity or from participating in the offering of any penny stock;"
        },
        {
          "type": "item",
          "text": "Is subject to any order of the SEC entered within five (5) years of the date of this Questionnaire that, at the time of subscription, orders the person to cease and desist from committing or causing a violation or future violation of (a) any scienter-based anti-fraud provisions of the federal securities laws, or (b) Section 5 of the Securities Act;"
        },
        {
          "type": "item",
          "text": "Is suspended or expelled from membership in, or suspended or barred from association with a member of, a registered national securities exchange or a registered national or affiliated securities association for any act or omission to act constituting conduct inconsistent with just and equitable principles of trade;"
        },
        {
          "type": "item",
          "text": "Has filed (as a registrant or issuer), or was named as an underwriter in, any registration statement or Regulation A offering statement filed with the SEC that, within five (5) years of the date of this Questionnaire, was the subject of a refusal order, stop order, or order suspending the Regulation A exemption, or is, at the time of subscription, the subject of an investigation or proceeding to determine whether such order should be issued; or"
        },
        {
          "type": "item",
          "text": "Is subject to a U.S. Postal Service false representation order entered within five (5) years of the date of this Questionnaire, or is, at the time of subscription, subject to a temporary restraining order or preliminary injunction with respect to conduct alleged by the U.S. Postal Service to constitute a scheme or device for obtaining money or property through the mail by means of false representations."
        },
        {
          "type": "p",
          "text": "Please check one:"
        },
        {
          "type": "p",
          "text": "[ ] None of the events described in (1) through (8) above is applicable to the Subscriber or any of its beneficial owners, control persons, principals, or affiliates."
        },
        {
          "type": "p",
          "text": "[ ] One or more of the events described in (1) through (8) above is or may be applicable. If checked, please describe in reasonable detail on a separate sheet attached hereto."
        },
        {
          "type": "p",
          "text": "The Subscriber agrees to promptly notify the Manager in writing if any of the events described above becomes applicable to the Subscriber or any of its beneficial owners, control persons, principals, or affiliates at any time prior to the Closing Date or thereafter."
        },
        {
          "type": "p",
          "text": "Part VI — FINRA and Other Affiliations"
        },
        {
          "type": "p",
          "text": "Please answer each of the following:"
        },
        {
          "type": "p",
          "text": "1. Is the Subscriber, or any beneficial owner of the Subscriber, an officer, director, partner, member, registered representative, employee, control person, or other affiliate of any Financial Industry Regulatory Authority (“FINRA”) member firm?"
        },
        {
          "type": "p",
          "text": "[ ] Yes"
        },
        {
          "type": "p",
          "text": "[ ] No"
        },
        {
          "type": "p",
          "text": "If yes, please identify the FINRA member firm and the nature of the affiliation:"
        },
        {
          "type": "p",
          "text": "Firm and Affiliation: _______________________________________________"
        },
        {
          "type": "p",
          "text": "2. Is the Subscriber a “foreign person” for purposes of the Foreign Investment Risk Review Modernization Act (FIRRMA) and the regulations administered by the Committee on Foreign Investment in the United States (CFIUS)?"
        },
        {
          "type": "p",
          "text": "[ ] Yes"
        },
        {
          "type": "p",
          "text": "[ ] No"
        },
        {
          "type": "p",
          "text": "3. Is the Subscriber a “government official,” “politically exposed person,” or related party to such persons (as defined in U.S. anti-corruption and anti-money laundering regulations)?"
        },
        {
          "type": "p",
          "text": "[ ] Yes"
        },
        {
          "type": "p",
          "text": "[ ] No"
        },
        {
          "type": "p",
          "text": "If yes, please describe:"
        },
        {
          "type": "p",
          "text": "Description: _______________________________________________"
        },
        {
          "type": "p",
          "text": "4. Will the Subscriber acquire the Subscribed Units, or any beneficial interest therein, on behalf of any other person?"
        },
        {
          "type": "p",
          "text": "[ ] No — the Subscriber is acquiring the Subscribed Units for the Subscriber’s own account."
        },
        {
          "type": "p",
          "text": "[ ] Yes — if checked, please provide details on a separate sheet."
        },
        {
          "type": "p",
          "text": "Part VII — IRS Tax Forms"
        },
        {
          "type": "p",
          "text": "The Subscriber agrees to provide, concurrently with this Questionnaire (or as soon as practicable thereafter), a properly completed and executed IRS Form W-9 (for U.S. persons) or the appropriate IRS Form W-8 series form (for non-U.S. persons), and such other tax forms, certifications, and documentation as the Manager or the Tax Representative may request from time to time."
        },
        {
          "type": "p",
          "text": "Please indicate which form the Subscriber is providing:"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-9 (U.S. person)"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-8BEN (non-U.S. individual beneficial owner)"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-8BEN-E (non-U.S. entity)"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-8ECI (income effectively connected with U.S. trade or business)"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-8EXP (foreign government, international organization, central bank, etc.)"
        },
        {
          "type": "p",
          "text": "[ ] IRS Form W-8IMY (intermediary or flow-through entity)"
        },
        {
          "type": "p",
          "text": "Part VIII — Certification"
        },
        {
          "type": "p",
          "text": "By executing this Questionnaire, the Subscriber hereby certifies that:"
        },
        {
          "type": "item",
          "text": "The information provided in this Questionnaire (and in any attachments hereto) is true, complete, and correct in all material respects, and the Subscriber understands that the Company, the Manager, and their respective counsel are entitled to rely upon the accuracy and completeness of such information for purposes of, among other things, qualifying the offer and sale of the Securities for an exemption from registration under the Securities Act and applicable state securities laws;"
        },
        {
          "type": "item",
          "text": "The Subscriber will promptly notify the Manager in writing of any change to any of the information provided in this Questionnaire that occurs prior to the Closing Date or, with respect to the Subscriber’s status as an accredited investor or as a Benefit Plan Investor, at any time during the period in which the Subscriber holds Class B Units;"
        },
        {
          "type": "item",
          "text": "The Subscriber understands that any false statement or material omission in this Questionnaire may result in the rejection of the Subscriber’s subscription, the termination of the Subscriber’s rights as a Member of the Company, civil and criminal liability under the Securities Act and other applicable laws, and indemnification obligations under Section 5 of the Subscription Agreement; and"
        },
        {
          "type": "item",
          "text": "The Subscriber consents to the Company’s and the Manager’s use of the information provided in this Questionnaire to comply with applicable securities, tax, anti-money laundering, sanctions, and other laws and regulations, and to disclose such information to their respective counsel, accountants, administrators, and other service providers as the Manager deems appropriate."
        },
        {
          "type": "p",
          "text": "[Signature page follows]"
        },
        {
          "type": "p",
          "text": "SIGNATURE PAGE TO ACCREDITED INVESTOR QUESTIONNAIRE"
        },
        {
          "type": "p",
          "text": "IN WITNESS WHEREOF, the undersigned has executed this Accredited Investor Questionnaire as of the date set forth below."
        },
        {
          "type": "p",
          "text": "FOR INDIVIDUAL SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Signature: {{signature}}"
        },
        {
          "type": "p",
          "text": "Print Name (Joint Subscriber, if any): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Signature (Joint Subscriber, if any): _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "FOR ENTITY SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Name of Entity: _______________________________________________"
        },
        {
          "type": "p",
          "text": "By: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Print Name of Authorized Signatory: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Title: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        }
      ],
      "panel": null
    },
    {
      "numeral": "EXHIBIT B",
      "title": "EXHIBIT B",
      "blocks": [
        {
          "type": "p",
          "text": "COUNTERPART SIGNATURE PAGE TO OPERATING AGREEMENT"
        },
        {
          "type": "p",
          "text": "By executing this counterpart signature page (this “Counterpart Signature Page”), the undersigned (the “Subscriber”) hereby:"
        },
        {
          "type": "item",
          "text": "Adopts, agrees to, and accepts all of the terms and conditions of the Operating Agreement of ASC Simphonic II, LLC, dated as of May 15, 2026 (as the same may be amended, supplemented, or restated from time to time, the “Operating Agreement”);"
        },
        {
          "type": "item",
          "text": "Makes each of the representations, warranties, and covenants set forth in Article 10 of the Operating Agreement, as if each such representation, warranty, and covenant were set forth in full herein;"
        },
        {
          "type": "item",
          "text": "Authorizes the Manager to amend Exhibit A and Schedule I to the Operating Agreement to reflect the Subscriber’s admission as a Member, the Subscriber’s capital contribution, the number of Class B Units issued to the Subscriber, and the Subscriber’s Percentage Interest; and"
        },
        {
          "type": "item",
          "text": "Acknowledges that, upon acceptance by the Manager, the Subscriber shall be admitted as a Member of ASC Simphonic II, LLC, holding Class B Units, and shall be bound by the Operating Agreement to the same extent as if the Subscriber had executed the Operating Agreement on the original execution date thereof."
        },
        {
          "type": "p",
          "text": "FOR INDIVIDUAL SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Signature: {{signature}}"
        },
        {
          "type": "p",
          "text": "Capital Contribution: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Number of Class B Units: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "FOR ENTITY SUBSCRIBERS:"
        },
        {
          "type": "p",
          "text": "Name of Entity: _______________________________________________"
        },
        {
          "type": "p",
          "text": "By: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Title: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Capital Contribution: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Number of Class B Units: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "ACKNOWLEDGED AND AGREED BY:"
        },
        {
          "type": "p",
          "text": "ASC SIMPHONIC II, LLC"
        },
        {
          "type": "p",
          "text": "By: AltSpot Capital, LLC, its Manager"
        },
        {
          "type": "p",
          "text": "By: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Print Name: {{legalName}}"
        },
        {
          "type": "p",
          "text": "Title: _______________________________________________"
        },
        {
          "type": "p",
          "text": "Date: _______________________________________________"
        },
        {
          "type": "p",
          "text": "[End of Subscription Agreement]"
        }
      ],
      "panel": null
    }
  ]
} as const;
